/*
 * Центр аутентификации
 * API демонстрационного приложения \"Центр аутентификации\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.peneksglazami.cassandra.demo.model.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Устанавливаемые новые параметры учетных записей
 */
@Schema(description = "Устанавливаемые новые параметры учетных записей")

public class UserGroupUpdateRequestNewSettings {
  @JsonProperty("activeBlockId")
  private String activeBlockId = null;

  public UserGroupUpdateRequestNewSettings activeBlockId(String activeBlockId) {
    this.activeBlockId = activeBlockId;
    return this;
  }

   /**
   * Идентификатор блока, к которому необходимо приписать учётную запись
   * @return activeBlockId
  **/
  @Schema(description = "Идентификатор блока, к которому необходимо приписать учётную запись")
  public String getActiveBlockId() {
    return activeBlockId;
  }

  public void setActiveBlockId(String activeBlockId) {
    this.activeBlockId = activeBlockId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserGroupUpdateRequestNewSettings userGroupUpdateRequestNewSettings = (UserGroupUpdateRequestNewSettings) o;
    return Objects.equals(this.activeBlockId, userGroupUpdateRequestNewSettings.activeBlockId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeBlockId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserGroupUpdateRequestNewSettings {\n");
    
    sb.append("    activeBlockId: ").append(toIndentedString(activeBlockId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
