/*
 * Центр аутентификации
 * API демонстрационного приложения \"Центр аутентификации\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.peneksglazami.cassandra.demo.model.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Фильтр для определения учетных записей
 */
@Schema(description = "Фильтр для определения учетных записей")

public class UserGroupUpdateRequestFilter {
  @JsonProperty("groupId")
  private String groupId = null;

  @JsonProperty("activeBlockId")
  private String activeBlockId = null;

  public UserGroupUpdateRequestFilter groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Идентификатор группы, к которому должна принадлежать учётная запись
   * @return groupId
  **/
  @Schema(description = "Идентификатор группы, к которому должна принадлежать учётная запись")
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public UserGroupUpdateRequestFilter activeBlockId(String activeBlockId) {
    this.activeBlockId = activeBlockId;
    return this;
  }

   /**
   * Идентификатор блока, к которому в настоящий момент приписаны учётная запись
   * @return activeBlockId
  **/
  @Schema(description = "Идентификатор блока, к которому в настоящий момент приписаны учётная запись")
  public String getActiveBlockId() {
    return activeBlockId;
  }

  public void setActiveBlockId(String activeBlockId) {
    this.activeBlockId = activeBlockId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserGroupUpdateRequestFilter userGroupUpdateRequestFilter = (UserGroupUpdateRequestFilter) o;
    return Objects.equals(this.groupId, userGroupUpdateRequestFilter.groupId) &&
        Objects.equals(this.activeBlockId, userGroupUpdateRequestFilter.activeBlockId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupId, activeBlockId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserGroupUpdateRequestFilter {\n");
    
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    activeBlockId: ").append(toIndentedString(activeBlockId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
